import os
import subprocess
import requests
from git import Repo
from openai import OpenAI

import index

client = OpenAI(api_key=index.OPENAI_API_KEY)


def clone_repository():
    if not os.path.exists("repo"):
        print("Cloning repository...")
        Repo.clone_from(index.REPO_URL, "repo")
    return Repo("repo")


def run_pylint():
    print("Running pylint...")
    result = subprocess.run(
        ["pylint", "repo"],
        capture_output=True,
        text=True
    )
    return result.stdout


def generate_fix(issue_text):
    print("Generating fix using AI...")

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "system",
                "content": "You are a Python expert. Fix the code issues."
            },
            {
                "role": "user",
                "content": issue_text
            }
        ]
    )

    return response.choices[0].message.content


# def apply_fix(code):
#     with open("repo/ai_fix.py", "w") as f:
#         f.write(code)


def create_commit(repo):
    print("Creating branch and commit...")

    branch = repo.create_head("ai-fix-branch")
    repo.head.reference = branch
    repo.head.reset(index=True, working_tree=True)

    repo.git.add(A=True)
    repo.index.commit("AI generated fix")

    repo.remote().push(branch)


def create_pull_request():

    url = f"https://api.github.com/repos/{index.REPO_OWNER}/{index.REPO_NAME}/pulls"

    data = {
        "title": "AI Automated Fix",
        "head": "ai-fix-branch",
        "base": index.BASE_BRANCH,
        "body": "This pull request was automatically generated by an AI agent."
    }

    headers = {
        "Authorization": f"token {index.GITHUB_TOKEN}"
    }

    response = requests.post(url, json=data, headers=headers)

    print("Pull request created:", response.json())


def main():
    repo = clone_repository()

    issues = run_pylint()

    # fix_code = generate_fix(issues)

    # apply_fix(fix_code)

    create_commit(repo)

    create_pull_request()


if __name__ == "__main__":
    main()